spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://monorail.proxy.rlwy.net:21428/railway}
    username: postgres
    password: ${PGPASSWORD:GdADGf*2BcdC1143cDBb-dFgedcba43d}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}