spring:
  datasource:
    url: ${POSTGREDATABASE}
    username: postgres
    password: ${POSTGREPASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}