spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:postgres:GdADGf*2BcdC1143cDBb-dFgedcba43d@:/railway}
    username: postgres
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}